version: "3.9"
services:
  node:
    image: nutsfoundation/nuts-node:v5.0.0
    environment:
      NUTS_CONFIGFILE: /opt/nuts/nuts.yaml
    ports:
      - 1323:1323
      - 5555:5555
    volumes:
      - "./nuts.yaml:/opt/nuts/nuts.yaml:ro"
      - "./data:/opt/nuts/data"
      - "./pki/certificate.pem:/opt/nuts/certificate.pem:ro"
      - "./pki/truststore.pem:/opt/nuts/truststore.pem:ro"